name: ui_common
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  lottie: ^3.1.0


dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/src/assets/
  integrations:
    lottie: true
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

#  fonts:
#    - family: Comic Neue
#      fonts:
#        - asset: assets/fonts/Comic-Neue.ttf